module.exports = function () {
  return {
    monsters: [
      {id: 1, name: "blaze", img: "images/monsters/Blaze.webp",isBoss: false, type: "hostile mob"},
      {id: 2, name: "chicken jockey", img: "images/monsters/Chicken_Husk_Jockey.webp",isBoss: false, type: "hostile mob"},
      {id: 3, name: "creeper", img: "images/monsters/Creeper.webp",isBoss: false, type: "hostile mob"},
      {id: 4, name: "zombie villager", img: "images/monsters/Zombie_Villager.webp",isBoss: false, type: "hostile mob"},
      {id: 5, name: "drowned", img: "images/monsters/Drowned.webp",isBoss: false, type: "hostile mob"},
      {id: 6, name: "elder guardian", img: "images/monsters/Elder_Guardian.webp",isBoss: false, type: "hostile mob"},
      {id: 7, name: "ender dragon", img: "images/monsters/Ender_Dragon.webp",isBoss: true, type: "hostile mob"},
      {id: 8, name: "enderman", img: "images/monsters/Enderman.webp",isBoss: false, type: "hostile mob"},
      {id: 9, name: "endermite", img: "images/monsters/Endermite.webp",isBoss: false, type: "hostile mob"},
      {id: 10, name: "evoker  summoning  vexes", img: "images/monsters/Evoker_Summoning_Vexes.webp",isBoss: false, type: "hostile mob"},
      {id: 11, name: "ghast", img: "images/monsters/Ghast.webp",isBoss: false, type: "hostile mob"},
      {id: 12, name: "guardian", img: "images/monsters/Guardian.webp",isBoss: false, type: "hostile mob"},
      {id: 13, name: "hoglin", img: "images/monsters/Hoglin.webp",isBoss: false, type: "hostile mob"},
      {id: 14, name: "husk", img: "images/monsters/Husk.webp",isBoss: false, type: "hostile mob"},
      {id: 15, name: "magma cube", img: "images/monsters/Magma_Cube.webp",isBoss: false, type: "hostile mob"},
      {id: 16, name: "phantom", img: "images/monsters/Phantom.webp",isBoss: false, type: "hostile mob"},
      {id: 17, name: "piglin", img: "images/monsters/Piglin.webp",isBoss: false, type: "hostile mob"},
      {id: 18, name: "piglin brute", img: "images/monsters/Piglin_Brute.webp",isBoss: false, type: "hostile mob"},
      {id: 19, name: "pillager", img: "images/monsters/Pillager.webp",isBoss: false, type: "hostile mob"},
      {id: 20, name: "ravager", img: "images/monsters/Ravager.webp",isBoss: false, type: "hostile mob"},
      {id: 21, name: "shulker", img: "images/monsters/Shulker.webp",isBoss: false, type: "hostile mob"},
      {id: 22, name: "silverfish", img: "images/monsters/Silverfish.webp",isBoss: false, type: "hostile mob"},
      {id: 23, name: "skeleton", img: "images/monsters/Skeleton.webp",isBoss: false, type: "hostile mob"},
      {id: 24, name: "skeleton horseman", img: "images/monsters/Skeleton_Trap.webp",isBoss: false, type: "hostile mob"},
      {id: 25, name: "slime", img: "images/monsters/Slime.webp",isBoss: false, type: "hostile mob"},
      {id: 26, name: "spider", img: "images/monsters/Spider.webp",isBoss: false, type: "hostile mob"},
      {id: 27, name: "cave spider", img: "images/monsters/Cave_Spider.webp",isBoss: false, type: "hostile mob"},
      {id: 28, name: "spider jockey", img: "images/monsters/Spider_Jockey.webp",isBoss: false, type: "hostile mob"},
      {id: 29, name: "stray", img: "images/monsters/Stray.webp",isBoss: false, type: "hostile mob"},
      {id: 30, name: "vex", img: "images/monsters/Vex.webp",isBoss: false, type: "hostile mob"},
      {id: 31, name: "vindicator", img: "images/monsters/Vindicator.webp",isBoss: false, type: "hostile mob"},
      {id: 32, name: "warden", img: "images/monsters/Warden.webp",isBoss: false, type: "hostile mob"},
      {id: 33, name: "witch", img: "images/monsters/Witch.webp",isBoss: false, type: "hostile mob"},
      {id: 34, name: "wither", img: "images/monsters/Wither.webp",isBoss: true, type: "hostile mob"},
      {id: 35, name: "wither skeleton", img: "images/monsters/Wither_Skeleton.webp",isBoss: false, type: "hostile mob"},
      {id: 36, name: "zoglin", img: "images/monsters/Zoglin.webp",isBoss: false, type: "hostile mob"},
      {id: 38, name: "zombie", img: "images/monsters/Zombie.webp",isBoss: false, type: "hostile mob"},
      {id: 40, name: "zombified piglin", img: "images/monsters/Zombified_Piglin.webp",isBoss: false, type: "hostile mob"},
    ]
  }
}